[package]
name = "nengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies]
windows = "0.39.0"

[build-dependencies]
bindgen = "0.60.1"
